#include <cstdint>

class alignas(64) __single_inheritance CPU {
private:
    uint8_t a, b, x, y, z, f;
    union {
        uint16_t p;
        struct {
            uint8_t h;
            uint8_t l;
        };
    } s, i;
    enum flags {
        CF = 0b00000001,
        OF = 0b00010000,
        ZF = 0b00100000,
        SF = 0b01000000,
        IF = 0b10000000
    };
    uint16_t addrBus;
    uint8_t  dataBus;
    bool     irq;
    bool     nmi;
    bool     rst;
private:
    uint16_t cycleCount = 0;
    uint8_t  addCyclePreemptable();
private:
    void     readMemoryByte(uint16_t addr, uint8_t & dest);
    void     readMemoryWord(uint16_t addr, uint16_t & dest);
    void     writeMemoryByte(uint16_t addr, uint8_t & src);
    void     writeMemoryWord(uint16_t addr, uint16_t & src);
    uint8_t  fetchImmByte();
    uint16_t fetchImmWord();
    void     pushByte(uint8_t val);
    void     pushWord(uint16_t val);
    uint8_t  popByte();
    uint16_t popWord();
    void     loop();
    void     FDE();
    void     reset();
    void     nmiInterrupt();
    void     irqInterrupt();
private:
    void FAULT_ILLEGAL();
    void FAULT_BUS();
private:
    void MOV_a_b();
    void MOV_a_iB();
    void MOV_a_dB();
    void MOV_a_zpdB();
    void MOV_a_zpxB();
    void MOV_a_zpyB();
    void MOV_a_zpzB();
    void MOV_a_izpxB();
    void MOV_a_izpyB();
    void MOV_a_izpzB();
    void MOV_a_dxB();
    void MOV_a_dyB();
    void MOV_a_dzB();
    void MOV_a_x();
    void MOV_a_y();
    void MOV_a_z();
    void MOV_b_a();
    void MOV_b_iB();
    void MOV_b_dB();
    void MOV_b_zpdB();
    void MOV_b_zpxB();
    void MOV_b_zpyB();
    void MOV_b_zpzB();
    void MOV_b_izpxB();
    void MOV_b_izpyB();
    void MOV_b_izpzB();
    void MOV_b_dxB();
    void MOV_b_dyB();
    void MOV_b_dzB();
    void MOV_b_x();
    void MOV_b_y();
    void MOV_b_z();
    void PUSH_a();
    void PUSH_b();
    void POP_a();
    void POP_b();
    void PUSHF();
    void POPF();
    void SETI();
    void CLRI();
    void SETC();
    void CLRC();
    void NOT_a();
    void NOT_b();
    void SSPH_iB();
    void NOP();
    void INT();
    void IRET();
    void RET();
    void JMP_d();
    void JMP_id();
    void JZ_iB();
    void JNZ_iB();
    void JC_iB();
    void JNC_iB();
    void JO_iB();
    void JNO_iB();
    void JS_iB();
    void JNS_iB();
    void SLX();
    void XSL();
    void TEST_a_b();
    void TEST_b_a();
    void TEST_a_iB();
    void TEST_b_iB();
    void CALL_d();
    void LSL_a();
    void LSL_b();
    void ASR_a();
    void ASR_b();
    void ROL_a();
    void ROL_b();
    void ROR_a();
    void ROR_b();
    void CMP_a_b();
    void CMP_a_iB();
    void CMP_a_zpxB();
    void CMP_a_zpyB();
    void CMP_a_zpzB();
    void CMP_b_a();
    void CMP_b_iB();
    void CMP_b_dxB();
    void CMP_b_dyB();
    void CMP_b_dzB();
    void AND_a_b();
    void AND_a_iB();
    void AND_a_dB();
    void AND_a_zpdB();
    void AND_a_zpxB();
    void AND_a_zpyB();
    void AND_a_zpzB();
    void AND_a_izpxB();
    void AND_a_izpyB();
    void AND_a_izpzB();
    void AND_a_dxB();
    void AND_a_dyB();
    void AND_a_dzB();
    void PUSH_x();
    void PUSH_y();
    void PUSH_z();
    void AND_b_a();
    void AND_b_iB();
    void AND_b_dB();
    void AND_b_zpdB();
    void AND_b_zpxB();
    void AND_b_zpyB();
    void AND_b_zpzB();
    void AND_b_izpxB();
    void AND_b_izpyB();
    void AND_b_izpzB();
    void AND_b_dxB();
    void AND_b_dyB();
    void AND_b_dzB();
    void POP_x();
    void POP_y();
    void POP_z();
    void OR_a_b();
    void OR_a_iB();
    void OR_a_dB();
    void OR_a_zpdB();
    void OR_a_zpxB();
    void OR_a_zpyB();
    void OR_a_zpzB();
    void OR_a_izpxB();
    void OR_a_izpyB();
    void OR_a_izpzB();
    void OR_a_dxB();
    void OR_a_dyB();
    void OR_a_dzB();
    void MOV_x_a();
    void MOV_y_a();
    void MOV_z_a();
    void OR_b_a();
    void OR_b_iB();
    void OR_b_dB();
    void OR_b_zpdB();
    void OR_b_zpxB();
    void OR_b_zpyB();
    void OR_b_zpzB();
    void OR_b_izpxB();
    void OR_b_izpyB();
    void OR_b_izpzB();
    void OR_b_dxB();
    void OR_b_dyB();
    void OR_b_dzB();
    void MOV_x_b();
    void MOV_y_b();
    void MOV_z_b();
    void XOR_a_b();
    void XOR_a_iB();
    void XOR_a_dB();
    void XOR_a_zpdB();
    void XOR_a_zpxB();
    void XOR_a_zpyB();
    void XOR_a_zpzB();
    void XOR_a_izpxB();
    void XOR_a_izpyB();
    void XOR_a_izpzB();
    void XOR_a_dxB();
    void XOR_a_dyB();
    void XOR_a_dzB();
    void INC_x();
    void INC_y();
    void INC_z();
    void XOR_b_a();
    void XOR_b_iB();
    void XOR_b_dB();
    void XOR_b_zpdB();
    void XOR_b_zpxB();
    void XOR_b_zpyB();
    void XOR_b_zpzB();
    void XOR_b_izpxB();
    void XOR_b_izpyB();
    void XOR_b_izpzB();
    void XOR_b_dxB();
    void XOR_b_dyB();
    void XOR_b_dzB();
    void DEC_x();
    void DEC_y();
    void DEC_z();
    void ADC_a_b();
    void ADC_a_iB();
    void ADC_a_dB();
    void ADC_a_zpdB();
    void ADC_a_zpxB();
    void ADC_a_zpyB();
    void ADC_a_zpzB();
    void ADC_a_izpxB();
    void ADC_a_izpyB();
    void ADC_a_izpzB();
    void ADC_a_dxB();
    void ADC_a_dyB();
    void ADC_a_dzB();
    void CMP_x_a();
    void CMP_y_a();
    void CMP_z_a();
    void ADC_b_a();
    void ADC_b_iB();
    void ADC_b_dB();
    void ADC_b_zpdB();
    void ADC_b_zpxB();
    void ADC_b_zpyB();
    void ADC_b_zpzB();
    void ADC_b_izpxB();
    void ADC_b_izpyB();
    void ADC_b_izpzB();
    void ADC_b_dxB();
    void ADC_b_dyB();
    void ADC_b_dzB();
    void CMP_x_b();
    void CMP_y_b();
    void CMP_z_b();
    void SBB_a_b();
    void SBB_a_iB();
    void SBB_a_dB();
    void SBB_a_zpdB();
    void SBB_a_zpxB();
    void SBB_a_zpyB();
    void SBB_a_zpzB();
    void SBB_a_izpxB();
    void SBB_a_izpyB();
    void SBB_a_izpzB();
    void SBB_a_dxB();
    void SBB_a_dyB();
    void SBB_a_dzB();
    void CMP_x_dB();
    void CMP_y_dB();
    void CMP_z_dB();
    void SBB_b_a();
    void SBB_b_iB();
    void SBB_b_dB();
    void SBB_b_zpdB();
    void SBB_b_zpxB();
    void SBB_b_zpyB();
    void SBB_b_zpzB();
    void SBB_b_izpxB();
    void SBB_b_izpyB();
    void SBB_b_izpzB();
    void SBB_b_dxB();
    void SBB_b_dyB();
    void SBB_b_dzB();
    void CMP_x_iB();
    void CMP_y_iB();
    void CMP_z_iB();
private:
    static inline void (CPU::*opTable[256])() = {

    };
};
